--VẤN TIN SẢN PHẨM--
SELECT * FROM CUNGCAP WHERE MASP = '00C1'
EXEC USP_VANTINSP '00C1'

----VẤN TIN ĐƠN ĐẶT HÀNG--
SELECT * FROM DONDH WHERE MADDH = '111'
EXEC USP_VANTINDDH '111'

----VẤN TIN ĐỊA CHỈ GIAO HÀNGG--
SELECT * FROM DONDH WHERE MADDH = '311'
EXEC USP_VANTINDCGH '311'