--CẬP NHẬT GIÁ CỦA SẢN PHẨM ĐƯỢC KHUYẾN MÃI
CREATE 
--ALTER
PROC USP_KHUYENMAI_FIX
    @MST CHAR(20),
    @MACN CHAR(20),
    @MASP CHAR(20),
	@CHIETKHAU FLOAT
AS
BEGIN TRAN    
	DECLARE @TENSP NVARCHAR(50) = (SELECT TENSP 
							        FROM SANPHAM 
							        WHERE MASP = @MASP)
    DECLARE @GIASP MONEY = (SELECT GIASP 
							FROM CUNGCAP with(UPDLOCK)
							WHERE   MST = @MST
                                AND MACHINHANH = @MACN
                                AND MASP = @MASP)
	PRINT N'GIÁ CỦA SẢN PHẨM ' + @TENSP + N' HIỆN TẠI: ' +  CAST(@GIASP AS CHAR(20))
	WAITFOR DELAY '0:0:05'

	BEGIN TRY
		UPDATE CUNGCAP
		SET GIASP = GIASP * (1 - @CHIETKHAU) -- CHIETKHAU trong khoảng [0, 1]
		WHERE MST = @MST
            AND MACHINHANH = @MACN
            AND MASP = @MASP

	END TRY
	BEGIN CATCH 
		DECLARE @ErrorMsg VARCHAR(2000)
		SELECT @ErrorMsg = N'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ErrorMsg, 16,1)
		ROLLBACK TRAN
		RETURN
	END CATCH
    PRINT N'GIÁ CỦA SẢN PHẨM ' + @TENSP + N' MỚI: ' +  CAST(@GIASP * (1 - @CHIETKHAU) AS CHAR(20))
    PRINT N'CẬP NHẬT GIÁ SẢN PHẨM THÀNH CÔNG'
COMMIT TRAN
GO

--ĐỐI TÁC MUỐN TĂNG GIÁ SẢN PHẨM
CREATE 
--ALTER
PROC USP_TANGGIA_FIX
	 @MST CHAR(20),
    @MACN CHAR(20),
    @MASP CHAR(20),
	@GIAMOI FLOAT
AS
BEGIN TRAN
	DECLARE @TENSP NVARCHAR(50) = (SELECT TENSP 
							        FROM SANPHAM 
							        WHERE MASP = @MASP)
    DECLARE @GIASP MONEY = (SELECT GIASP
							FROM CUNGCAP with(UPDLOCK) 
							WHERE   MST = @MST
                                AND MACHINHANH = @MACN
                                AND MASP = @MASP)
	PRINT N'GIÁ CỦA SẢN PHẨM ' + @TENSP + N' HIỆN TẠI: ' +  CAST(@GIASP AS CHAR(20))
	WAITFOR DELAY '0:0:05'

	BEGIN TRY
		UPDATE CUNGCAP
		SET GIASP = @GIAMOI
		WHERE MST = @MST
            AND MACHINHANH = @MACN
            AND MASP = @MASP

	END TRY
	BEGIN CATCH 
		DECLARE @ErrorMsg VARCHAR(2000)
		SELECT @ErrorMsg = N'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ErrorMsg, 16,1)
		ROLLBACK TRAN
		RETURN
	END CATCH
	 PRINT N'GIÁ CỦA SẢN PHẨM ' + @TENSP + N' MỚI: ' +  CAST(@GIAMOI AS CHAR(20))
    PRINT N'CẬP NHẬT GIÁ SẢN PHẨM THÀNH CÔNG'
COMMIT TRAN