--Lấy danh sách chi nhánh của DOITAC
CREATE 
--ALTER
PROC USP_LayDSCN_FIX
    @MST CHAR(20)
AS
BEGIN TRAN
    SET TRAN ISOLATION LEVEL SERIALIZABLE -- Prevent inserting new rows into the key range
    DECLARE @SLCN INT, @MACN char(24), @DIACHI nvarchar(200)
    
	BEGIN TRY
		DECLARE cur CURSOR DYNAMIC FOR SELECT MACHINHANH, DIACHI 
                                        FROM CHINHANH
		                                WHERE   MST = @MST
		OPEN CUR
		SET @SLCN = (SELECT COUNT(*)
						FROM CHINHANH
                        WHERE   MST = @MST)

        /*SELECT @@SPID
        SELECT * FROM sys.dm_tran_locks
        WHERE request_session_id = @@SPID*/
		SELECT * FROM CHINHANH  WHERE  MST = @MST
		WAITFOR DELAY '0:0:10'

	    PRINT N'SỐ CHI NHÁNH CỦA ĐỐI TÁC: ' + @MST  + CAST(@SLCN AS VARCHAR(10))
	    PRINT N'THÔNG TIN CHI NHÁNH CỦA ĐỐI TÁC ' + @MST
	    PRINT N'MÃ CHI NHÁNH						ĐỊA CHỈ'
		FETCH NEXT FROM CUR INTO @MACN, @DIACHI
		WHILE (@@FETCH_STATUS = 0)
		BEGIN
			PRINT @MACN + @DIACHI
			--WAITFOR DELAY '0:0:02'
			FETCH NEXT FROM CUR INTO @MACN, @DIACHI
		END
		CLOSE CUR
		DEALLOCATE CUR
	END TRY
	BEGIN CATCH
		DECLARE @ErrorMsg VARCHAR(2000)
		SELECT @ErrorMsg = N'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ErrorMsg, 16,1)
		ROLLBACK TRAN
		RETURN
	END CATCH
COMMIT TRAN

GO
--THÊM TÀI KHOẢN
--CREATE
ALTER
PROC USP_THEMCHINHANH
	@MST CHAR(20),
	@MACN CHAR(20),
	@DIACHI NVARCHAR(200)
AS
BEGIN TRAN
	DECLARE @DAIDIEN NVARCHAR(50) = (SELECT NGUOIDAIDIEN FROM DOITAC WHERE MST = @MST)

	BEGIN TRY
		IF (NOT EXISTS(SELECT * FROM CHINHANH WHERE MACHINHANH = @MACN))
		BEGIN
			INSERT CHINHANH(MST, NGUOIDAIDIEN, MACHINHANH, DIACHI)
			VALUES (@MST, @DAIDIEN, @MACN, @DIACHI)
		END
		ELSE 
		BEGIN
			PRINT N'CHI NHÁNH NÀY ĐÃ TỒN TẠI'
			ROLLBACK TRAN
			RETURN
		END
		--WAITFOR DELAY '0:0:05'
	END TRY
	BEGIN CATCH
		DECLARE @ErrorMsg VARCHAR(2000)
		SELECT @ErrorMsg = N'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ErrorMsg, 16,1)
		ROLLBACK TRAN
		RETURN
	END CATCH
	PRINT N'ĐÃ THÊM THÀNH CÔNG'
COMMIT TRAN
GO