-- UNREPEAT CASE01
SELECT * FROM HOPDONG WHERE MST = (SELECT MST FROM HOPDONG WHERE MAHD = '00B')
EXEC USP_TRUYVANHD '0191818716', '2021/07/07'


-- UNREPEAT CASE02
SELECT * FROM SANPHAM WHERE TENSP = N'bơ'
EXEC USP_TRUYVANSP N'bơ'


-- UNREPEAT CASE03
SELECT * FROM NGUOIDUNG
EXEC USP_DANGNHAP 'TaiXe', 'TaiXe'