--KHÁCH HÀNG TÌM SẢN PHẨM
--CREATE 
ALTER 
PROC USP_TRUYVANSP
	@TENSP NVARCHAR(200)
AS
BEGIN TRAN
    SET TRAN ISOLATION LEVEL REPEATABLE READ -- get S, keep until commit
	BEGIN TRY
		IF(NOT EXISTS (SELECT * FROM SANPHAM WHERE TENSP = @TENSP))
		BEGIN
			PRINT N'SẢN PHẨM ' + @TENSP + N' KHÔNG TỒN TẠI'
			ROLLBACK TRAN
			RETURN
		END
		
		WAITFOR DELAY '0:0:05'
		IF(NOT EXISTS (SELECT * FROM SANPHAM WHERE TENSP = @TENSP))
		BEGIN
			PRINT N'SẢN PHẨM ' + @TENSP + N' KHÔNG TỒN TẠI'
			ROLLBACK TRAN
			RETURN
		END
		
		SELECT * FROM SANPHAM WHERE TENSP = @TENSP
	END TRY
	BEGIN CATCH
		RAISERROR (N'LỖI HỆ THỐNG',16,1)
		ROLLBACK TRAN
		RETURN
	END CATCH
COMMIT TRAN
GO


--THAY ĐỔI TÊN SẢN PHẨM
--CREATE 
ALTER 
PROC USP_DOITENSP
	@MASP CHAR(20),
	@TENSPCU NVARCHAR(200),
	@TENSPMOI NVARCHAR(200)
AS
BEGIN TRAN
	BEGIN TRY
		IF(EXISTS(SELECT * FROM SANPHAM WHERE MASP = @MASP AND TENSP = @TENSPCU))
			UPDATE SANPHAM
			SET TENSP = @TENSPMOI
			WHERE MASP = @MASP
		ELSE 
		BEGIN
			PRINT N'KHÔNG TÌM THẤY SẢN PHẨM ' + @TENSPCU
			ROLLBACK TRAN
			RETURN
		END
	END TRY
	BEGIN CATCH
		RAISERROR (N'LỖI HỆ THỐNG',16,1)
		ROLLBACK TRAN
		RETURN
	END CATCH
COMMIT TRAN