--- --- --- --- --- --- --- --- --- DIRTY READ --- --- --- --- --- --- --- --- ---
-- Dirty CASE 01
CREATE
-- ALTER
PROC USP_CAPNHATGIASP -- Cập nhật giá của sản phẩm
    @MST CHAR(20),
	@CHINHANH CHAR(20),
    @MASP CHAR(20),
    @SOTIEN INT
AS
BEGIN TRAN
    UPDATE CUNGCAP
    SET GIASP = @SOTIEN
    WHERE   MASP = @MASP
        AND MST = @MST
        AND MACHINHANH = @CHINHANH

    WAITFOR DELAY '00:00:10'
ROLLBACK TRAN
GO

CREATE
--ALTER
PROC USP_VANTINSP -- VẤN TIN SẢN PHẨM
    @MASP CHAR(20)
AS
BEGIN TRAN
    SET TRAN ISOLATION LEVEL READ UNCOMMITTED --READ WITH NO S LOCK
    BEGIN TRY
        SELECT * FROM CUNGCAP WHERE MASP = @MASP
    END TRY
    BEGIN CATCH
        DECLARE @ERRORMSG NVARCHAR(1000)
        SET @ERRORMSG = N'LỖI : ' + ERROR_MESSAGE()
        RAISERROR (@ERRORMSG, 16,1)
        ROLLBACK TRAN
        RETURN
    END CATCH
    PRINT N'VẤN TIN SẢN PHẨM THÀNH CÔNG'
COMMIT TRAN
GO


-- Dirty CASE 02
CREATE
-- ALTER
PROC USP_CAPNHATDDH -- Cập nhật tình trạng đơn đặt hàng
    @MADDH CHAR(20),
    @TINHTRANG NVARCHAR(20)
AS
BEGIN TRAN
    UPDATE DONDH
    SET TINHTRANG = @TINHTRANG
    WHERE MADDH = @MADDH

    WAITFOR DELAY '00:00:10'
ROLLBACK TRAN
GO

CREATE
--ALTER
PROC USP_VANTINDDH -- VẤN TIN ĐƠN ĐẶT HÀNG
    @MADDH CHAR(20)
AS
BEGIN TRAN
    SET TRAN ISOLATION LEVEL READ UNCOMMITTED --READ WITH NO S LOCK
    DECLARE @TRANGTHAI NVARCHAR(50) = ''
    BEGIN TRY
        SET @TRANGTHAI = (SELECT TINHTRANG
                            FROM DONDH
                            WHERE MADDH = @MADDH)
        PRINT N'TRẠNG THÁI HIỆN TẠI CỦA ĐƠN HÀNG ' + @MADDH + ' : ' + @TRANGTHAI

    END TRY
    BEGIN CATCH
        DECLARE @ERRORMSG NVARCHAR(1000)
        SET @ERRORMSG = N'LỖI : ' + ERROR_MESSAGE()
        RAISERROR (@ERRORMSG, 16,1)
        ROLLBACK TRAN
        RETURN
    END CATCH
    PRINT N'VẤN TIN ĐƠN ĐẶT HÀNG THÀNH CÔNG'
COMMIT TRAN
GO


-- Dirty CASE 03
CREATE
-- ALTER
PROC USP_CAPNHATDCGH -- Thay đổi địa chỉ giao hàng
    @MADDH CHAR(20),
    @DIACHIMOI NVARCHAR(200)
AS
BEGIN TRAN
    UPDATE DONDH
    SET DIACHIGIAOHANG = @DIACHIMOI
    WHERE   MADDH = @MADDH

    WAITFOR DELAY '00:00:10'
ROLLBACK TRAN
GO

CREATE
--ALTER
PROC USP_VANTINDCGH --VẤN TIN ĐỊA CHỈ GIAO HÀNG
    @MADDH CHAR(20)
AS
BEGIN TRAN
    SET TRAN ISOLATION LEVEL READ UNCOMMITTED --READ WITH NO S LOCK

    BEGIN TRY
        SELECT * FROM DONDH WHERE MADDH = @MADDH
    END TRY
    BEGIN CATCH
        DECLARE @ERRORMSG NVARCHAR(1000)
        SET @ERRORMSG = N'LỖI : ' + ERROR_MESSAGE()
        RAISERROR (@ERRORMSG, 16,1)
        ROLLBACK TRAN
        RETURN
    END CATCH
    PRINT N'VẤN TIN ĐỊA CHỈ GIAO HÀNG THÀNH CÔNG'
COMMIT TRAN
GO


--- --- --- --- --- --- --- --- UNREPEATABLE READ --- --- --- --- --- --- --- ---
-- Unrepeat CASE 01
CREATE 
--ALTER 
PROC USP_TRUYVANHD -- TRUY VẤN HỢP ĐỒNG VỚI THỜI GIAN KẾT THÚC
	@MADT CHAR(20),
	@HETHAN DATETIME
	
AS
BEGIN TRAN
	BEGIN TRY
		IF(NOT EXISTS (SELECT * FROM HOPDONG WHERE MST = @MADT))
		BEGIN
			PRINT N'KHÔNG TÌM THẤY HỢP ĐỒNG CỦA ĐỐI TÁC ' + @MADT
			ROLLBACK TRAN
			RETURN
		END

		WAITFOR DELAY '0:0:05'

		IF(NOT EXISTS (SELECT * FROM HOPDONG WHERE MST = @MADT AND THGIANHIEULUC = @HETHAN))
		BEGIN
			PRINT N'KHÔNG TÌM THẤY HỢP ĐỒNG CÓ HIỆU LỰC ĐẾN NGÀY ' + CAST(@HETHAN AS VARCHAR(20))
			ROLLBACK TRAN
			RETURN
		END
		
		SELECT * FROM HOPDONG WHERE MST = @MADT AND THGIANHIEULUC = @HETHAN

	END TRY
	BEGIN CATCH
		RAISERROR (N'LỖI HỆ THỐNG',16,1)
		ROLLBACK TRAN
		RETURN
	END CATCH
COMMIT TRAN
GO

CREATE 
--ALTER 
PROC USP_GIAHANHD --THAY ĐỔI THỜI GIAN HIỆU LỰC CHO HỢP ĐỒNG
	@MAHD CHAR(20),
	@THOIHANCU CHAR(10),
	@THOIHANMOI CHAR(10)
AS
BEGIN TRAN
	BEGIN TRY
		IF(EXISTS(SELECT * FROM HOPDONG WHERE MAHD = @MAHD AND THGIANHIEULUC = @THOIHANCU))
			UPDATE HOPDONG
			SET THGIANHIEULUC = @THOIHANMOI, KICHHOAT = 1
			WHERE MAHD = @MAHD
		ELSE 
		BEGIN
			PRINT N'KHÔNG TÌM THẤY HỢP ĐỒNG CÓ HIỆU LỰC NGÀY ' + CAST(@THOIHANCU AS VARCHAR(20))
			ROLLBACK TRAN
			RETURN
		END

	END TRY
	BEGIN CATCH
		RAISERROR (N'LỖI HỆ THỐNG',16,1)
		ROLLBACK TRAN
		RETURN
	END CATCH
COMMIT TRAN
GO


-- Unrepeat CASE 02
CREATE 
--ALTER 
PROC USP_TRUYVANSP -- TRUY VẤN SẢN PHẨM
	@TENSP NVARCHAR(200)
AS
BEGIN TRAN
	BEGIN TRY
		IF(NOT EXISTS (SELECT * FROM SANPHAM WHERE TENSP = @TENSP))
		BEGIN
			PRINT N'SẢN PHẨM: ' + @TENSP + N' KHÔNG TỒN TẠI'
			ROLLBACK TRAN
			RETURN
		END
		
		WAITFOR DELAY '0:0:05'
		IF(NOT EXISTS (SELECT * FROM SANPHAM WHERE TENSP = @TENSP))
		BEGIN
			PRINT N'SẢN PHẨM: ' + @TENSP + N' KHÔNG TỒN TẠI'
			ROLLBACK TRAN
			RETURN
		END
		
		SELECT * FROM SANPHAM WHERE TENSP = @TENSP
	END TRY
	BEGIN CATCH
		RAISERROR (N'LỖI HỆ THỐNG',16,1)
		ROLLBACK TRAN
		RETURN
	END CATCH
COMMIT TRAN
GO

CREATE 
--ALTER 
PROC USP_DOITENSP --THAY ĐỔI TÊN SẢN PHẨM
	@MASP CHAR(20),
	@TENSPCU NVARCHAR(200),
	@TENSPMOI NVARCHAR(200)
AS
BEGIN TRAN
	BEGIN TRY
		IF(EXISTS(SELECT * FROM SANPHAM WHERE MASP = @MASP AND TENSP = @TENSPCU))
			UPDATE SANPHAM
			SET TENSP = @TENSPMOI
			WHERE MASP = @MASP
		ELSE 
		BEGIN
			PRINT N'KHÔNG TÌM THẤY SẢN PHẨM ' + @TENSPCU
			ROLLBACK TRAN
			RETURN
		END
	END TRY
	BEGIN CATCH
		RAISERROR (N'LỖI HỆ THỐNG',16,1)
		ROLLBACK TRAN
		RETURN
	END CATCH
COMMIT TRAN
GO


-- Unrepeat CASE 03
CREATE 
--ALTER 
PROC USP_DANGNHAP --ĐĂNG NHẬP VÀO HỆ THỐNG
	@TAIKHOAN VARCHAR(200),
	@MATKHAU VARCHAR(200)
AS
BEGIN TRAN
	BEGIN TRY
		IF(NOT EXISTS (SELECT * FROM NGUOIDUNG WHERE TAIKHOAN = @TAIKHOAN))
		BEGIN
			PRINT @TAIKHOAN + N' KHÔNG TỒN TẠI'
			ROLLBACK TRAN
			RETURN
		END

		WAITFOR DELAY '0:0:05'

		IF(NOT EXISTS(SELECT * FROM NGUOIDUNG WHERE TAIKHOAN = @TAIKHOAN AND MATKHAU = @MATKHAU))
		BEGIN
			PRINT N'SAI MẬT KHẨU'
			ROLLBACK TRAN
			RETURN
		END

		SELECT * FROM NGUOIDUNG WHERE TAIKHOAN = @TAIKHOAN AND MATKHAU = @MATKHAU
		PRINT N'ĐĂNG NHẬP THÀNH CÔNG'
	END TRY
	BEGIN CATCH
		RAISERROR (N'LỖI HỆ THỐNG',16,1)
		ROLLBACK TRAN
		RETURN
	END CATCH
COMMIT TRAN
GO

CREATE 
--ALTER 
PROC USP_DOIMATKHAU --THAY ĐỔI MẬT KHẨU
	@TAIKHOAN VARCHAR(200),
	@MATKHAUMOI VARCHAR(200)
AS
BEGIN TRAN
	DECLARE @MATKHAUCU VARCHAR(200) = (SELECT MATKHAU 
										FROM NGUOIDUNG WHERE TAIKHOAN = @TAIKHOAN)
	BEGIN TRY
		IF(EXISTS(SELECT * FROM NGUOIDUNG WHERE TAIKHOAN = @TAIKHOAN AND MATKHAU = @MATKHAUCU))
			UPDATE NGUOIDUNG
			SET MATKHAU = @MATKHAUMOI
			WHERE TAIKHOAN = @TAIKHOAN
		ELSE 
		BEGIN
			PRINT N'LỖI ĐĂNG NHẬP'
			ROLLBACK TRAN
			RETURN
		END
	END TRY
	BEGIN CATCH
		RAISERROR (N'LỖI HỆ THỐNG',16,1)
		ROLLBACK TRAN
		RETURN
	END CATCH
COMMIT TRAN
GO


--- --- --- --- --- --- --- --- --- PHANTOM READ --- --- --- --- --- --- --- --- ---
-- Phantom CASE 01
CREATE 
--ALTER
PROC USP_LayDSSP --Lấy danh sách sản phẩm
AS
BEGIN TRAN
--default isolation level: not prevent T2 insert new rows
    DECLARE @SLSP INT, @MASP VARCHAR(20), @TENSP NVARCHAR(200)
	BEGIN TRY
		DECLARE cur CURSOR DYNAMIC FOR SELECT MASP, TENSP 
                                        FROM SANPHAM
		OPEN CUR
		SET @SLSP = (SELECT COUNT(*) FROM SANPHAM)

	    PRINT N'TỔNG SẢN PHẨM: ' + CAST(@SLSP AS VARCHAR(10))
        WAITFOR DELAY '0:0:05'

		FETCH NEXT FROM CUR INTO @MASP, @TENSP
		WHILE (@@FETCH_STATUS = 0)
		BEGIN
			PRINT @MASP + ' : ' + @TENSP
			
			FETCH NEXT FROM CUR INTO @MASP, @TENSP
		END
		CLOSE CUR
		DEALLOCATE CUR
	END TRY
	BEGIN CATCH
		DECLARE @ErrorMsg VARCHAR(2000)
		SELECT @ErrorMsg = N'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ErrorMsg, 16,1)
		ROLLBACK TRAN
		RETURN
	END CATCH
COMMIT TRAN

GO

CREATE
--ALTER
PROC USP_THEMSANPHAM --THÊM SẢN PHẨM
	@MASP CHAR(20),
	@TENSP NVARCHAR(200)
AS
BEGIN TRAN
	BEGIN TRY
		IF (NOT EXISTS(SELECT * FROM SANPHAM WHERE MASP = @MASP))
		BEGIN
			INSERT SANPHAM(MASP, TENSP)
			VALUES (@MASP, @TENSP)
		END
		ELSE 
		BEGIN
			PRINT N'SẢN PHẨM NÀY ĐÃ TỒN TẠI'
			ROLLBACK TRAN
			RETURN
		END

	END TRY
	BEGIN CATCH
		DECLARE @ErrorMsg VARCHAR(2000)
		SELECT @ErrorMsg = N'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ErrorMsg, 16,1)
		ROLLBACK TRAN
		RETURN
	END CATCH
	PRINT N'ĐÃ THÊM THÀNH CÔNG'
COMMIT TRAN
GO


-- Phantom CASE 02
CREATE 
--ALTER
PROC USP_LayDSDT --Lấy danh sách các đối tác đã đăng ký
AS
BEGIN TRAN
--default isolation level: not prevent T2 insert new rows
    DECLARE @SLDT INT,@MST CHAR(20),@DAIDIEN NVARCHAR(50),@TENDT NVARCHAR(50)
	BEGIN TRY
		DECLARE cur CURSOR DYNAMIC FOR SELECT MST, NGUOIDAIDIEN, TENDT FROM DOITAC
		OPEN CUR
		SET @SLDT = (SELECT COUNT(*) FROM DOITAC)

	    PRINT N'TỔNG SỐ ĐỐI TÁC HIỆN CÓ: ' + CAST(@SLDT AS VARCHAR(10))
        WAITFOR DELAY '0:0:05'

		PRINT N'DANH SÁCH CÁC ĐỐI TÁC ĐÃ KÝ HỢP ĐỒNG'
		PRINT SPACE(4) + 'MST'  + SPACE(15) + N'TÊN ĐỐI TÁC' +  SPACE(3) + N'NGƯỜI ĐẠI DIỆN'
		
		FETCH NEXT FROM CUR INTO @MST, @DAIDIEN, @TENDT
		WHILE (@@FETCH_STATUS = 0)
		BEGIN
			PRINT @MST + ' : ' + @TENDT  + char(9) + ' ; ' +  @DAIDIEN
			
			FETCH NEXT FROM CUR INTO @MST, @DAIDIEN, @TENDT
		END
		CLOSE CUR
		DEALLOCATE CUR
	END TRY
	BEGIN CATCH
		DECLARE @ErrorMsg VARCHAR(2000)
		SELECT @ErrorMsg = N'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ErrorMsg, 16,1)
		ROLLBACK TRAN
		RETURN
	END CATCH
COMMIT TRAN
GO

CREATE
--ALTER
PROC USP_THEMDOITAC --THÊM ĐỐI TÁC
	@MST CHAR(20),
	@DAIDIEN NVARCHAR(50),
	@TENDT NVARCHAR(50),
	@SLCN INT,
	@LOAIHANG NVARCHAR(50),
	@DIACHI NVARCHAR(200),
	@SDT CHAR(10),
	@EMAIL CHAR(50)
AS
BEGIN TRAN
	BEGIN TRY
		IF (NOT EXISTS(SELECT * FROM DOITAC WHERE MST = @MST))
		BEGIN
			INSERT DOITAC(MST,NGUOIDAIDIEN,TENDT,SLCHINHANH,LOAIHANG,DIACHI,SDT,EMAIL)
			VALUES (@MST,@DAIDIEN,@TENDT,@SLCN,@LOAIHANG,@DIACHI,@SDT,@EMAIL)
		END
		ELSE 
		BEGIN
			PRINT N'ĐỐI TÁC NÀY ĐÃ TỒN TẠI'
			ROLLBACK TRAN
			RETURN
		END
		
	END TRY
	BEGIN CATCH
		DECLARE @ErrorMsg VARCHAR(2000)
		SELECT @ErrorMsg = N'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ErrorMsg, 16,1)
		ROLLBACK TRAN
		RETURN
	END CATCH
	PRINT N'ĐÃ THÊM THÀNH CÔNG'
COMMIT TRAN
GO


-- Phantom CASE 03
CREATE 
--ALTER
PROC USP_LayDSCN --Lấy danh sách chi nhánh của DOITAC
    @MST CHAR(20)
AS
BEGIN TRAN
--default isolation level: not prevent T2 insert new rows
    DECLARE @SLCN INT, @MACN char(24), @DIACHI nvarchar(200) 
    
	BEGIN TRY
		DECLARE cur CURSOR DYNAMIC FOR SELECT MACHINHANH, DIACHI 
                                        FROM CHINHANH
		                                WHERE MST = @MST
		OPEN CUR
		SET @SLCN = (SELECT COUNT(*)
						FROM CHINHANH
                        WHERE   MST = @MST)

	    PRINT N'TỔNG SỐ CHI NHÁNH CỦA ĐỐI TÁC CÓ MST ' + @MST + ' : ' + CAST(@SLCN AS VARCHAR(10))

		WAITFOR DELAY '0:0:05'

	    PRINT N'THÔNG TIN CHI NHÁNH CỦA ĐỐI TÁC CÓ MST ' + @MST
	    PRINT N'MÃ CHI NHÁNH' + SPACE(12) + N'ĐỊA CHỈ'
		FETCH NEXT FROM CUR INTO @MACN, @DIACHI
		WHILE (@@FETCH_STATUS = 0)
		BEGIN
			PRINT @MACN + @DIACHI
			FETCH NEXT FROM CUR INTO @MACN, @DIACHI
		END
		CLOSE CUR
		DEALLOCATE CUR
	END TRY
	BEGIN CATCH
		DECLARE @ErrorMsg VARCHAR(2000)
		SELECT @ErrorMsg = N'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ErrorMsg, 16,1)
		ROLLBACK TRAN
		RETURN
	END CATCH
COMMIT TRAN
GO

CREATE
--ALTER
PROC USP_THEMCHINHANH --THÊM CHI NHÁNH
	@MST CHAR(20),
	@MACN CHAR(20),
	@DIACHI NVARCHAR(200)
AS
BEGIN TRAN
	DECLARE @DAIDIEN NVARCHAR(50) = (SELECT NGUOIDAIDIEN FROM DOITAC WHERE MST = @MST)

	BEGIN TRY
		IF (NOT EXISTS(SELECT * FROM CHINHANH WHERE MACHINHANH = @MACN))
		BEGIN
			INSERT CHINHANH(MST, NGUOIDAIDIEN, MACHINHANH, DIACHI)
			VALUES (@MST, @DAIDIEN, @MACN, @DIACHI)
		END
		ELSE 
		BEGIN
			PRINT N'CHI NHÁNH NÀY ĐÃ TỒN TẠI'
			ROLLBACK TRAN
			RETURN
		END
		
	END TRY
	BEGIN CATCH
		DECLARE @ErrorMsg VARCHAR(2000)
		SELECT @ErrorMsg = N'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ErrorMsg, 16,1)
		ROLLBACK TRAN
		RETURN
	END CATCH
	PRINT N'ĐÃ THÊM THÀNH CÔNG'
COMMIT TRAN
GO


--- --- --- --- --- --- --- --- --- LOST UPDATE --- --- --- --- --- --- --- --- ---
-- Lost Update CASE 01
CREATE
--ALTER
PROC USP_PHIHH_HANGTHANG --CẬP NHẬT PHÍ HOA HỒNG ĐỊNH KỲ 1 THÁNG
	@MST CHAR(20),
	@MAHD CHAR(20),
	@SOTIEN MONEY
AS
BEGIN TRAN
	DECLARE @PHIHH MONEY = (SELECT PHIHOAHONG
							FROM HOPDONG 
							WHERE MST = @MST AND MAHD = @MAHD)
	PRINT N'PHÍ HOA HỒNG HIỆN TẠI: ' + CAST(@PHIHH AS CHAR(20))
	WAITFOR DELAY '0:0:05'

	BEGIN TRY
		UPDATE HOPDONG
		SET PHIHOAHONG = @SOTIEN + PHIHOAHONG
		WHERE MST = @MST AND MAHD = @MAHD

	END TRY
	BEGIN CATCH 
		DECLARE @ErrorMsg VARCHAR(2000)
		SELECT @ErrorMsg = N'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ErrorMsg, 16,1)
		ROLLBACK TRAN
		RETURN
	END CATCH
	PRINT N'PHÍ HOA HỒNG MỚI : ' + CAST((@SOTIEN + @PHIHH) AS CHAR(20))
	PRINT N'CẬP NHẬT PHÍ HÀNG THÁNG THÀNH CÔNG'
COMMIT TRAN
GO

CREATE 
--ALTER
PROC USP_PHIHH_HANGNAM --CẬP NHẬT PHÍ HOA HỒNG ĐỊNH KỲ 1 NĂM
	@MST CHAR(20),
	@MAHD CHAR(20),
	@SOTIEN MONEY
AS
BEGIN TRAN
	DECLARE @PHIHH MONEY = (SELECT PHIHOAHONG
							FROM HOPDONG 
							WHERE MST = @MST AND MAHD = @MAHD)

	PRINT N'PHÍ HOA HỒNG HIỆN TẠI: ' + CAST(@PHIHH AS CHAR(20))
	
	BEGIN TRY
		UPDATE HOPDONG
		SET PHIHOAHONG = @SOTIEN + PHIHOAHONG
		WHERE MST = @MST AND MAHD = @MAHD
	END TRY
	BEGIN CATCH 
		DECLARE @ErrorMsg VARCHAR(2000)
		SELECT @ErrorMsg = N'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ErrorMsg, 16,1)
		ROLLBACK TRAN
		RETURN
	END CATCH
	PRINT N'PHÍ HOA HỒNG MỚI : ' + CAST((@SOTIEN + @PHIHH) AS CHAR(20))
	PRINT N'CẬP NHẬT PHÍ HÀNG NĂM THÀNH CÔNG'
COMMIT TRAN
GO


-- Lost Update CASE 02
CREATE 
--ALTER
PROC USP_CAPNHATNGUOIDAIDIEN --CẬP NHẬT NGƯỜI ĐẠI DIỆN
	@MST CHAR(20),
    @DAIDIENMOI NVARCHAR(50)
AS
BEGIN TRAN
	DECLARE @DAIDIEN NVARCHAR(50) = (SELECT NGUOIDAIDIEN
							        FROM DOITAC 
							        WHERE MST = @MST)
	PRINT N'NGƯỜI ĐẠI DIỆN HIỆN TẠI: ' + @DAIDIEN
	WAITFOR DELAY '0:0:05'

	BEGIN TRY
		UPDATE DOITAC
		SET NGUOIDAIDIEN = @DAIDIENMOI
		WHERE MST = @MST

        UPDATE HOPDONG
		SET NGUOIDAIDIEN = @DAIDIENMOI
		WHERE MST = @MST

        UPDATE DANGKY
		SET NGUOIDAIDIEN = @DAIDIENMOI
		WHERE MST = @MST

        UPDATE CHINHANH
		SET NGUOIDAIDIEN = @DAIDIENMOI
		WHERE MST = @MST

	END TRY
	BEGIN CATCH 
		DECLARE @ErrorMsg VARCHAR(2000)
		SELECT @ErrorMsg = N'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ErrorMsg, 16,1)
		ROLLBACK TRAN
		RETURN
	END CATCH
	PRINT N'NGƯỜI ĐẠI DIỆN : ' + @DAIDIENMOI
	PRINT N'CẬP NHẬT NGƯỜI ĐẠI DIỆN THÀNH CÔNG'
COMMIT TRAN
GO


-- Lost Update CASE 03
CREATE 
--ALTER
PROC USP_KHUYENMAI --CẬP NHẬT GIÁ CỦA SẢN PHẨM ĐƯỢC KHUYẾN MÃI
    @MST CHAR(20),
    @MACN CHAR(20),
    @MASP CHAR(20),
	@CHIETKHAU FLOAT
AS
BEGIN TRAN
	DECLARE @TENSP NVARCHAR(50) = (SELECT TENSP
							        FROM SANPHAM 
							        WHERE MASP = @MASP)
    DECLARE @GIASP MONEY = (SELECT GIASP
							FROM CUNGCAP 
							WHERE   MST = @MST
                                AND MACHINHANH = @MACN
                                AND MASP = @MASP)
	PRINT N'GIÁ CỦA SẢN PHẨM ' + @TENSP + N' HIỆN TẠI: ' +  CAST(@GIASP AS CHAR(20))
	WAITFOR DELAY '0:0:05'

	BEGIN TRY
		UPDATE CUNGCAP
		SET GIASP = GIASP * (1 - @CHIETKHAU) -- CHIETKHAU trong khoảng [0, 1]
		WHERE MST = @MST
            AND MACHINHANH = @MACN
            AND MASP = @MASP

	END TRY
	BEGIN CATCH 
		DECLARE @ErrorMsg VARCHAR(2000)
		SELECT @ErrorMsg = N'Lỗi: ' + ERROR_MsỐESSAGE()
		RAISERROR(@ErrorMsg, 16,1)
		ROLLBACK TRAN
		RETURN
	END CATCH
    PRINT N'GIÁ CỦA SẢN PHẨM ' + @TENSP + N' MỚI: ' +  CAST(@GIASP * (1 - @CHIETKHAU) AS CHAR(20))
    PRINT N'CẬP NHẬT GIÁ SẢN PHẨM THÀNH CÔNG'
COMMIT TRAN
GO

CREATE 
--ALTER
PROC USP_TANGGIA --ĐỐI TÁC MUỐN TĂNG GIÁ SẢN PHẨM
	 @MST CHAR(20),
    @MACN CHAR(20),
    @MASP CHAR(20),
	@GIAMOI FLOAT
AS
BEGIN TRAN
	DECLARE @TENSP NVARCHAR(50) = (SELECT TENSP
							        FROM SANPHAM 
							        WHERE MASP = @MASP)
    DECLARE @GIASP MONEY = (SELECT GIASP
							FROM CUNGCAP 
							WHERE   MST = @MST
                                AND MACHINHANH = @MACN
                                AND MASP = @MASP)
	PRINT N'GIÁ CỦA SẢN PHẨM ' + @TENSP + N' HIỆN TẠI: ' +  CAST(@GIASP AS CHAR(20))
	
	BEGIN TRY
		UPDATE CUNGCAP
		SET GIASP = @GIAMOI
		WHERE MST = @MST
            AND MACHINHANH = @MACN
            AND MASP = @MASP

	END TRY
	BEGIN CATCH 
		DECLARE @ErrorMsg VARCHAR(2000)
		SELECT @ErrorMsg = N'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ErrorMsg, 16,1)
		ROLLBACK TRAN
		RETURN
	END CATCH
	 PRINT N'GIÁ CỦA SẢN PHẨM ' + @TENSP + N' MỚI: ' +  CAST(@GIAMOI AS CHAR(20))
    PRINT N'CẬP NHẬT GIÁ SẢN PHẨM THÀNH CÔNG'
COMMIT TRAN
GO